name: CI Tests
on: workflow_dispatch

jobs:
  build:
    name: CI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout tools
        uses: actions/checkout@v3
        with:
          node-version: 16.15.1
          cache: 'npm'
      - run: npm ci
      - name: Build Tools run
        run: npm run test:issueVc
      - name: Store test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports
          path: ./docs/reports/